# Generated by Django 6.0.6 on 2026-06-16 17:10

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_passage_question_passage'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='passage',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
